[features]
seeds = false
skip-lint = false
[programs.localnet]
remigroup = "79FsDa6rQT7ATFyQcZna56VEdDBcimcsehaPB7ktxtZe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "/Users/trongcauta/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
